import NavDrawer from '@/components/NavDrawer'
import '@/styles/globals.css'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return <div>
    <NavDrawer>
      <Component {...pageProps} />  
      </NavDrawer>
    <Head>
        <title>APN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  </div>
}
